export const ActionTypes = {

  SUBSCRIBE_TO_KEYWORD: 'SUBSCRIBE_TO_KEYWORD',
  KEYWORD_INPUT_CHANGE: 'KEYWORD_INPUT_CHANGE',
  SHOW_TWEETS_FOR_KEYWORD_ID: 'SHOW_TWEETS_FOR_KEYWORD_ID',
  INITIALIZE_KEYWORDS: 'INITIALIZE_KEYWORDS',
  CHANGE_SELECTED_KEYWORD_ID: 'CHANGE_SELECTED_KEYWORD_ID',
  UPDATE_SENTIMENTS: 'UPDATE_SENTIMENTS'

}
